server:
  port: 8080 #端口号

spring:
  application:
    name: microServiceCloudGateway  #服务注册中心注册的服务名

  cloud:
    gateway: #网关路由配置
      discovery:
        locator:
          enabled: true #默认值为 true，即默认开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: provider_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://MICROSERVICECLOUDPROVIDER #动态路由，使用服务名代替上面的具体带端口   http://eureka7001.com:9527/dept/list

          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/user/login    #断言，路径匹配 注意：Path 中 P 为大写
#            - Method=GET #只能时 GET 请求时，才能访问
        - id: consumer_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://MICROSERVICECLOUDCONSUMER #动态路由，使用服务名代替上面的具体带端口   http://eureka7001.com:9527/dept/list
          predicates:
            - Path=/**

eureka:
  instance:
    instance-id: springcloud-gateway-8080
    hostname: springcloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/